### ISSUE TITLE
Changes to Docker Hub Autobuild per June 18th, 2021

### ISSUE THREAD

**Issue by vweevers** [prebuild/docker-images#16]
> As one of the users of Docker Hub's Autobuild service, we wanted to reach out and let you know that from June 18th, 2021 users on the free plan will no longer have access to the Autobuild feature. This means that any of your currently configured Autobuild will fail to run and you will need to upgrade to a Pro or Team account to restore functionality. You can read more about the changes on [our blog](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/)

Seems like we should apply to the open source program:

> If you’re part of the [Docker Open Source program](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/), and currently leveraging Autobuilds as part of a Free plan, we want to continue supporting you and we will be reaching out to make sure you will not be impacted by this change.

Do we qualify?

> To qualify for the Open Source Program status, all the repos within the Publisher’s Docker namespace must:
>
> - [x] Be public and non-commercial
> - [x] Meet the Open Source Initiative (OSI) definition (shown [here](https://opensource.org/docs/osd)), including definitions for free distribution, source code, derived works, integrity of source code, licensing and no tolerance for discrimination 
> - [x] Distribute images under OSI [approved open source license](https://opensource.org/licenses/alphabetical)
> - [ ] Produce Docker images used to run applications

Not sure about the last one. What kind of image is _not_ running an application? 🤔 

Well, let's apply and we'll find out.

**Comment by vweevers** [comment]
Questions to answer on the Docker Open Source Community Application:

- **Reason for creating this project**
  Cross-compiling prebuilt binaries for Node.js addons
- **The types of user(s) that benefit from this project**
  npm package authors and their end users
- **The number of users you estimate benefit from this project**
  According to GitHub, 128K repositories depend on dependents of `prebuildify-cross`. Weekly npm downloads for the dependents of `prebuildify-cross` total roughly 1M. How do you translate that to a user count?

**Comment by ralphtheninja** [comment]
Since we can't know an end user count that's in any way accurate, I think we should only show the stats we do know of. E.g. download counts from npm, dependent packages and dependents of dependents.

**Comment by vweevers** [comment]
There's no room on the form for any explanation, just a single number:

![image](https://user-images.githubusercontent.com/3055345/121244771-90d27900-c89f-11eb-8b66-b93ff49b8541.png)

**Comment by vweevers** [comment]
How about we answer with a range? E.g. `10K-100K`

**Comment by ralphtheninja** [comment]
Sure!

**Comment by vweevers** [comment]
Submitted.

**Comment by vweevers** [comment]
No longer need Docker Hub or Autobuild: https://github.com/prebuild/docker-images/pull/19.
