### ISSUE TITLE
Create android-arm and android-arm64 images

### ISSUE THREAD

**Issue by vweevers** [prebuild/docker-images#2]
See also https://github.com/Level/leveldown/pull/587#issuecomment-457943370. They must have:

`ENV GYP_DEFINES target_arch=arm(64) android_target_arch=arm(64) host_os=linux OS=android`.

Note:

- IIRC you only need quotes around the value if you use the `GYP_DEFINES=` form, rather than `GYP_DEFINES<space>`
- `OS` must be uppercase
- `target_arch` might not be necessary, because we're also passing an `ARCH` (I didn't test without yet)

**Comment by ralphtheninja** [comment]
We might not need `target_arch` since `prebuildify` sets it here https://github.com/prebuild/prebuildify/blob/master/index.js#L124

**Comment by ralphtheninja** [comment]
https://github.com/prebuild/docker-images/commit/dc3a112ee2c61115d856a687c1d7380bd1884cd2 and
https://github.com/prebuild/docker-images/commit/bd98af328403fde7e1037406632268c98603fafe
