### ISSUE TITLE
Linux x86 image

### ISSUE THREAD

**Issue by thegecko** [prebuild/docker-images#21]
Would a linux-x86 image be of interest?

Following this project, I've created a `linux-x86` flavour:

https://github.com/node-usb/docker-images/blob/main/linux-x86/Dockerfile

Happy to contribute if it would be useful to others.

**Comment by vweevers** [comment]
Does Node.js support linux 32-bit?

**Comment by vweevers** [comment]
Node.js dropped it: https://github.com/nodejs/build/issues/885. So for now (although unofficial builds are available and compiling from source still works) I prefer not including it here. At least until more folks express interest - because the situation is the same for e.g. Android.
